apiVersion: v1
kind: ReplicationController
metadata:
  name: myonline-rc
spec:
  replicas: 2
  selector:
    app: myonlineapp-rc
    version: 2.6.2
  template:
    metadata:
      labels:
        app: myonlineapp-rc
        version: 2.6.2
    spec:
      containers:
        - name: myonlineapp_container
          image: maludockerhub/myimg28feb:1
          ports:
            - containerPort: 8080