apiVersion: v1
kind: ReplicationController
metadata:
  name: myonline-rc
spec:
  replicas: 2
  selector:
    app: myonlineapp
    version: 2.6.1
  template:
    metadata:
      labels:
        app: myonlineapp
        version: 2.6.1
    spec:
      containers:
        - name: myonlineapp-container
          image: maludockerhub/myimage28feb23
          ports:
            - containerPort: 8080