apiVersion: v1
kind: ReplicationController
metadata:
  name: myonlineapp-rc
spec:
  replicas: 2
  selector:
    app: myonstore
    version: 2.6.2
  template:
    metadata: 
      labels:
        app: myonstore
        version: 2.6.2
    spec:
      containers:
        - name: myonlineapp-container
          image: maludockerhub/myimage17march23
          ports:
            - containerPort: 8080