apiVersion: v1
kind: ReplicationController
metadata:
  name: myonlineapprc
spec:
  replicas: 3
  selector:
    app: myonlineapp
    version: 2.6.2
  template:
    metadata:
      labels:
        app: myonlineapp
        version: 2.6.2
    spec:
      containers:
        - name: myonlineapp_container
          image: maludockerhub/myimg28feb:1
          ports:
            - containerPort: 8080
