apiVersion: v1
kind: Service
metadata:
  name:  my-service
  labels: 
    app: myonstore
    version: 2.6.2 
spec:
  type:  NodePort
  ports:
  - port:  8080
    nodePort: 30001
    protocol: TCP
  selector:
    app:  myonstore
    version: 2.6.2 